### ISSUE TITLE
__rerum @context

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/rerum_server#25]
If a user submits data without an @context, we should put a RERUM generated @context into __rerum.  We need to generate a RERUM context file this IRI resolves to.  The point would be to describe our __rerum options and describe general objects we expect (like sc:Manifest perhaps) in cases where the user did not provide this.  This will help in some of our LD considerations.

**Comment by cubap** [comment]
always have an @context into __rerum, yeah? It is not likely the main object will describe `__rerum` for us. Here's a list to start:

- _Name_ is the helpful name we started with
- _Label_ is the actual label used in the property (may evolve)
- _Vocab_ is the external or home-rolled rdf
- _Description_ is our wordy explanation

Name | Label | Vocab | description | notes
---      | ---     | ---       | --- | ---
created  | created    |  dcterms:created   | The xsd:Date that this specific object was created | (milliseconds)
isOverwritten |  isOverwritten | dcterms:modifed | The most recent xsd:Date that this specific object was forcibly overwritten instead of versioned |  (milliseconds) May not exist? or may be NULL...
generatedBy | generator | as:generator | The application whose API key wrote this object | Reference to the Agent we created on their behalf
isReleased |  isReleased | dcterms:issued | The most recent xsd:Date that this specific object was `released` as described elsewhere |  (milliseconds) May not exist? or may be NULL... Also there is no setting here for "in progress", though the main object _should_ set an `oa:motivation` flag for it.
release.previous | release.previous | dcterms:isVersionOf | The first upstream version of this object that `isReleased` | This gets tricky...
release.previous | release.previous | dcterms:replaces | The first upstream version of this object that `isReleased` | ... because if this version `isReleased` then it suggests that it is a replacement, not just a version.
history.prime | history.prime | dcterms:isVersionOf | The very first novel version of this object | There may be a need for a custom or more refined description here to explain its original-ness.
history.previous | history.previous | prov:wasRevisionOf | The single upstream object from which this was created | This vocab indicates revisions share substantial content, which should be a safe assumption. This is also `oa:previousVersion`.
history.next | history.next | prov:hadRevision | All versions derived from this object | Maybe dcterms:hasVersion is better. There also isn't a sense of direct adjacency here, but that might not be needed.
service | annotationService | oa:annotationService | The RERUM API endpoint that was used | This suggests use of the same endpoint in the future, but that isn't really possible with RERUM and seems biased towards annotations, so maybe this is not helpful? What replaces it?

All we need to have for this right now is:

- oa: "http://www.w3.org/ns/oa#",
- dcterms: "http://purl.org/dc/terms/",
- xsd: "http://www.w3.org/2001/XMLSchema#",
- as: "http://www.w3.org/ns/activitystreams#"
- prov: "https://www.w3.org/ns/prov#"

but these could be useful in some of the values and may be included...

- sc: "http://iiif.io/api/presentation/2#",
- iiif: "http://iiif.io/api/image/2#",
- exif: "http://www.w3.org/2003/12/exif/ns#",
- dc: "http://purl.org/dc/elements/1.1/",
- dctypes: "http://purl.org/dc/dcmitype/",
- doap: "http://usefulinc.com/ns/doap#",
- foaf: "http://xmlns.com/foaf/0.1/",
- rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
- rdfs: "http://www.w3.org/2000/01/rdf-schema#",
- svcs: "http://rdfs.org/sioc/services#"

**Comment by cubap** [comment]
https://www.w3.org/TR/json-ld/#h3_interpreting-json-as-json-ld

Ordinary JSON documents can be interpreted as JSON-LD by referencing a JSON-LD context document in an HTTP Link Header. Doing so allows JSON to be unambiguously machine-readable without requiring developers to drastically change their documents and provides an upgrade path for existing infrastructure without breaking existing clients that rely on the `application/json` media type or a media type with a `+json` suffix as defined in [RFC6839](https://www.w3.org/TR/json-ld/#bib-RFC6839).

**Comment by thehabes** [comment]
http://devstore.rerum.io/v1/context.json
